# Generated by Django 2.1.7 on 2019-03-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20190305_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='contact',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
    ]
