# Generated by Django 2.1.7 on 2019-03-09 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='photo',
        ),
    ]
