# Generated by Django 2.1.7 on 2019-03-09 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_remove_cart_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='user_id',
            field=models.IntegerField(blank=True, default=None),
            preserve_default=False,
        ),
    ]
