# Generated by Django 2.1.7 on 2019-03-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_cart_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='image',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
