# Generated by Django 2.1.7 on 2019-03-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_cart_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='image',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
